# PyTorch Playground

In [3]:
import torch


In [2]:
if torch.cuda.is_available():
    print("Full power!")
    dev = torch.set_default_device("cuda")
else:
    print("Regular power..")
    dev = torch.set_default_device("cpu")

torch.get_default_device()

Full power!


device(type='cuda', index=0)

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2136, 0.2830, 0.0809],
        [0.9517, 0.2373, 0.2925],
        [0.2729, 0.1981, 0.2897],
        [0.9818, 0.6174, 0.1825],
        [0.6364, 0.9640, 0.7782]], device='cuda:0')


In [7]:
# Conv testing

m = torch.nn.Conv1d(16, 33, 3, stride=2)
input = torch.randn(20, 16, 50)
output = m(input)

print(input.shape)
output.shape

torch.Size([20, 16, 50])


torch.Size([20, 33, 24])

In [10]:
m = torch.nn.Dropout(p=0.2)
input = torch.randn(20, 16)
output = m(input)

print(input.shape)
output.shape

torch.Size([20, 16])


torch.Size([20, 16])

In [14]:
a = torch.ones((5, 10))
print(a)
torch.cumsum(a, dim=1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [17]:
def sequence_mask(lengths, maxlen = None, dtype=torch.bool):
    if maxlen is None:
        maxlen = lengths.max()
    mask = ~(torch.ones((len(lengths), maxlen)).cumsum(dim=1).t() > lengths).t()
    mask.type(dtype)
    return mask

In [21]:
sequence_mask(torch.IntTensor([1, 2, 3, 4, 5, 6, 7]), 10)

tensor([[ True, False, False, False, False, False, False, False, False, False],
        [ True,  True, False, False, False, False, False, False, False, False],
        [ True,  True,  True, False, False, False, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True, False, False, False]])